version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_ticketing
      MYSQL_USER: ballerina
      MYSQL_PASSWORD: ballerina123
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  passenger-service:
    build: ./passenger_service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ballerina
      DB_PASSWORD: ballerina123
      DB_NAME: smart_ticketing
      KAFKA_URL: kafka:9092
      HTTP_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - kafka

  ticketing-service:
    build: ./ticketing_service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ballerina
      DB_PASSWORD: ballerina123
      DB_NAME: smart_ticketing
      KAFKA_URL: kafka:9092
      HTTP_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - kafka
